### ISSUE TITLE
Xbox availability

### ISSUE THREAD

**Issue by rdnrtms** [NeverSinkDev/NeverSink-Filter-for-PoE2#19]
Hey, I read your README stating that it is shipped with the console version by default, but it is unfortunately not for me. Do you have a fix for that, like reinstalling or something? Thanks in advance! Good work though!

**Comment by Vikijaka** [comment]
Based on https://github.com/NeverSinkDev/NeverSink-PoE2litefilter/blob/main/README.md

Why do you think Path of Exile 2 litefilter is "shipped with the console version by default"?

**Comment by NoteThatHard** [comment]
> Hey, I read your README stating that it is shipped with the console version by default, but it is unfortunately not for me. Do you have a fix for that, like reinstalling or something? Thanks in advance! Good work though!

What @Vikijaka probably means is that this filter is still in an initial stage, as it hasn't even been a week since the Path of Exile 2 Early Access has launched, so it isn't shipped with the game as of now. 
The README piece of text - "This script (NeverSink's Filter) is shipped on the console versions of the game." - where you got that information is probably just copied and pasted from NeverSink's PoE1 item filter (it even calls it "NeverSink's Filter" and not "NeverSink's PoE2 Lite Filter"), so it is kind of  misleading.
Hopefully, it will be integrated once both the game and the filter are in a more advanced stage of development.

**Comment by rdnrtms** [comment]
Yeah, I read the README, and I did not assume that it was for PoE. It's absolutely fine if it's not working, I did not expect it to, I was just curious, because I'd like to use filters on xbox. Thanks for the replies, I'm closing this for now.
