### ISSUE TITLE
FeatureRequest: filter only bad bases

### ISSUE THREAD

**Issue by Void-fun** [NeverSinkDev/NeverSink-Filter-for-PoE2#41]
While I was playing Poe2, I noticed that all high level bases start with the word “EXPERT”. For example, if I am looking for “GOTHIC QUATERSTAFF” bases for a recombinator, I will only pick up bases that are called “EXPERT GOTHIC QUATERSTAFF”. And I will not pick bases with the names “GOTHIC QUATERSTAFF”, “ADVANCED GOTHIC QUATERSTAFF”, because they have bad flat damage values. 

Is there any possibility to make such filters that will highlight only the bases I need?

**Comment by GundlachApp** [comment]
You can just add some lines to it, so the good bases get highlited - dublicate for "Magic" and "Rare"
(you also could name those you'd wish to hide)

`Show
Rarity Normal
BaseType "Expert Long Quarterstaff" "Expert Gothic Quarterstaff" "Expert Crescent Quarterstaff" "Expert Slicing Quarterstaff"
PlayEffect Yellow
SetFontSize 52`

edit: I attached my custom version: No low base shown, and increaslingly better highlighted due to base level and rarity
[NeverSinks_Quaterstaff.txt](https://github.com/user-attachments/files/18181448/NeverSinks_Quaterstaff.txt)

**Comment by Void-fun** [comment]
Done, now it works!
Thank you so much!
