### ISSUE TITLE
There is no glowing border

### ISSUE THREAD

**Issue by Iowerth** [NeverSinkDev/NeverSink-Filter-for-PoE2#50]
Hi. I'm using the latest version 0.2.2 and I don't see glowing borders (as on your screenshot - Scroll of Wisdom, etc), only solid line borders (on screenshot - Regal Orb, etc). How to enable glowing?
<details>
  <summary>Click</summary>

![9vHIlICP4P](https://github.com/user-attachments/assets/d2f2d807-906d-4555-95a6-2cc60984c8db)
</details>

Instead I have this:
<details>
  <summary>Click</summary>

![f3OvuETjDg](https://github.com/user-attachments/assets/a57cdc4a-c23a-4b0c-8040-8664ead43658)
</details>

**Comment by logger24** [comment]
In 0.1.1 scroll of wisdom had the line:

```
Show
Class "Currency"
BaseType "Scroll of Wisdom" "Shard"
```

In 0.2.1 scroll of wisdom's line is now:

```
Show
Class "Currency"
BaseType "Wisdom" "Shard"

```

It's possibly on purpose, but also possible that "Wisdom" was a mistype instead of "Scroll of Wisdom", but I don't know anything about filters.
Either that or you're area level 65+ and it's hiding them possibly, but you're overriding them being hidden so they still show and has something to do with that?

From 0.2.1, added line:

```
Hide
BaseType "Scroll of Wisdom"
AreaLevel >= 65
Rarity <= Magic
```

Anyway, hope it gets look into if you can't figure it out, although scrolls of wisdom... are pretty pointless.

This is all I could gather by comparing the differences between the two versions.

Anyway I'd probably put a bet on the "Wisdom" vs "Scroll of Wisdom", whether on purpose or not.

Also, sidenote: The reason I'm saying 0.2.1 is because although the release file is 0.2.2; the version in the file is 0.2.1, so keep in mind I downloaded the 0.2.2 zip, for reference.

**Comment by Iowerth** [comment]
@logger24 seems you are not about what I wrote.

**Comment by logger24** [comment]
> @logger24 seems you are not about what I wrote.

You're right after trying to reread the original post, as it's very unclear, I'll step out of this one.
I played after posting with the latest 0.2.1/0.2.2 and it worked and looked as intended for me, so the filter is fine.
Best of luck finding a solution to what you're experiencing.

**Comment by Iowerth** [comment]
I found that it is not a loot filter issue.
